# Generated by Django 4.2.2 on 2023-06-07 19:55

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[base.validators.MyRegexValidator('[a-zA-Z]+', 'Name can only contain letters and numbers!')])),
                ('surname', models.CharField(max_length=200, validators=[base.validators.MyRegexValidator('[a-zA-Z]+', 'Surname can only contain letters and numbers!')])),
                ('age', models.PositiveIntegerField(validators=[base.validators.RangeValidator(12, 100, 'Age should be in range (12, 100)')])),
                ('language', models.CharField(max_length=255, validators=[base.validators.languageValidator])),
                ('email', models.CharField(max_length=255, validators=[base.validators.emailValidator])),
                ('favorite_game', models.CharField(max_length=255, validators=[base.validators.MyRegexValidator('[\\w\\s]+', 'Incorrect game name!')])),
                ('favorite_genre', models.CharField(max_length=255, validators=[base.validators.MyRegexValidator('[\\w\\s]+', 'Incorrect genre!')])),
                ('favorite_beverage', models.CharField(max_length=255, validators=[base.validators.beverageValidator])),
                ('club_rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[base.validators.ratingValidator])),
                ('device', models.CharField(max_length=255, validators=[base.validators.deviceValidator])),
            ],
        ),
    ]
