# Generated by Django 4.2.2 on 2023-06-07 20:30

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubuser',
            name='password',
            field=models.CharField(default=1, max_length=255, validators=[base.validators.MyRegexValidator('(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*#?&])[a-zA-Z\\d@$!%*#?&]{8,}', 'Password should containMinimum eight characters, at least one letter, one number and one special character')]),
            preserve_default=False,
        ),
    ]
